# Site settings
title: "Portfolio"
email: "nsharma1901@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://niv-sha.github.io/Website/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
